name = "DesertIslandDisk"
uuid = "4b41362c-03b0-4ba3-ab04-b4a602531e19"
authors = ["mahiki <mahiki@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
